# Generated by Django 5.1.6 on 2025-03-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tripmate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female")],
                max_length=10,
            ),
        ),
    ]
