# Generated by Django 5.1.6 on 2025-03-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tripmate", "0003_post_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True),
        ),
    ]
