# Generated by Django 2.2.28 on 2025-03-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripmate', '0006_auto_20250327_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_friends_+', to='tripmate.UserProfile'),
        ),
    ]
